# .github/workflows/deploy.yml
name: NuxtJS ShadCN Project

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main # deploy only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_PUBLIC_API_BASE_URL: "https://dj-dev.exlitem.com"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "NUXT_PUBLIC_API_BASE_URL=https://dj-dev.exlitem.com" >> .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt app for GitHub Pages
        run: npx nuxt generate --preset github_pages
        env:
          NUXT_APP_BASE_URL: /${{ github.event.repository.name }}
          NUXT_PUBLIC_API_BASE_URL: "https://dj-dev.exlitem.com"

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # allow deployment to Pages
      id-token: write   # required for OIDC
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
